# Generated by Django 5.1.1 on 2024-09-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_utilisateur_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='sex',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], default='Homme', max_length=30, null=True),
        ),
    ]
