# Generated by Django 5.1.1 on 2024-09-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_utilisateur_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sex',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], default='Homme', max_length=30, null=True),
        ),
    ]
