# Generated by Django 5.1.1 on 2024-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='est_publie',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
