# Generated by Django 5.1.1 on 2024-09-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_article_est_publie'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='est_commentaire',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
